-- Практическое занятие 20 использует MongoDB, поэтому SQL-схема не требуется.
-- Структура документа описана в Mongoose-модели User в server.js:
-- id INTEGER, first_name STRING, last_name STRING, age INTEGER,
-- created_at UNIX TIMESTAMP, updated_at UNIX TIMESTAMP.
