require("dotenv").config();

const cors = require("cors");
const dns = require("node:dns");
const express = require("express");
const path = require("node:path");
const { Pool } = require("pg");

dns.setDefaultResultOrder("ipv4first");

const app = express();
const PORT = Number(process.env.PORT) || 3000;
const HOST = process.env.HOST || "0.0.0.0";
const ROOT_DIR = __dirname;
const connectionString = process.env.DATABASE_URL || process.env.SUPABASE_DB_URL;

if (!connectionString) {
  console.error(
    "DATABASE_URL не задан. Создайте .env на основе .env.example и добавьте строку подключения Supabase.",
  );
  process.exit(1);
}

const pool = new Pool({
  connectionString,
  ssl:
    process.env.DB_SSL === "false"
      ? false
      : {
          rejectUnauthorized: false,
        },
});

app.use(cors());
app.use(express.json());
app.use(express.static(ROOT_DIR));

function parsePositiveInt(value) {
  const id = Number(value);
  return Number.isInteger(id) && id > 0 ? id : null;
}

function sanitizeUserPayload(body, { partial = false } = {}) {
  const payload = {};
  const errors = [];

  if (!partial || Object.hasOwn(body, "first_name")) {
    const firstName = String(body.first_name || "").trim();
    if (!firstName) {
      errors.push("first_name обязателен.");
    } else if (firstName.length > 80) {
      errors.push("first_name должен быть не длиннее 80 символов.");
    } else {
      payload.first_name = firstName;
    }
  }

  if (!partial || Object.hasOwn(body, "last_name")) {
    const lastName = String(body.last_name || "").trim();
    if (!lastName) {
      errors.push("last_name обязателен.");
    } else if (lastName.length > 80) {
      errors.push("last_name должен быть не длиннее 80 символов.");
    } else {
      payload.last_name = lastName;
    }
  }

  if (!partial || Object.hasOwn(body, "age")) {
    const age = Number(body.age);
    if (!Number.isInteger(age) || age < 0 || age > 130) {
      errors.push("age должен быть целым числом от 0 до 130.");
    } else {
      payload.age = age;
    }
  }

  if (partial && Object.keys(payload).length === 0 && errors.length === 0) {
    errors.push("Передайте хотя бы одно поле для обновления.");
  }

  return { payload, errors };
}

async function initDatabase() {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      first_name VARCHAR(80) NOT NULL,
      last_name VARCHAR(80) NOT NULL,
      age INTEGER NOT NULL CHECK (age >= 0 AND age <= 130),
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
  `);

  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_users_last_name
      ON users (last_name);
  `);

  await pool.query(`
    CREATE OR REPLACE FUNCTION set_users_updated_at()
    RETURNS TRIGGER AS $$
    BEGIN
      NEW.updated_at = NOW();
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
  `);

  await pool.query(`
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1
        FROM pg_trigger
        WHERE tgname = 'trg_users_updated_at'
      ) THEN
        CREATE TRIGGER trg_users_updated_at
        BEFORE UPDATE ON users
        FOR EACH ROW
        EXECUTE FUNCTION set_users_updated_at();
      END IF;
    END
    $$;
  `);
}

app.get("/api/health", async (request, response) => {
  try {
    const { rows } = await pool.query("SELECT NOW() AS db_time");
    response.json({ ok: true, databaseTime: rows[0].db_time });
  } catch (error) {
    response.status(503).json({
      ok: false,
      message: "Нет подключения к PostgreSQL/Supabase.",
      detail: error.message,
    });
  }
});

app.post("/api/users", async (request, response) => {
  const { payload, errors } = sanitizeUserPayload(request.body);

  if (errors.length) {
    response.status(400).json({ message: "Ошибка валидации.", errors });
    return;
  }

  try {
    const { rows } = await pool.query(
      `
        INSERT INTO users (first_name, last_name, age)
        VALUES ($1, $2, $3)
        RETURNING id, first_name, last_name, age, created_at, updated_at;
      `,
      [payload.first_name, payload.last_name, payload.age],
    );

    response.status(201).json(rows[0]);
  } catch (error) {
    response.status(500).json({ message: "Не удалось создать пользователя.", detail: error.message });
  }
});

app.get("/api/users", async (request, response) => {
  const search = String(request.query.search || "").trim();

  try {
    const query = search
      ? {
          text: `
            SELECT id, first_name, last_name, age, created_at, updated_at
            FROM users
            WHERE first_name ILIKE $1 OR last_name ILIKE $1
            ORDER BY id DESC;
          `,
          values: [`%${search}%`],
        }
      : {
          text: `
            SELECT id, first_name, last_name, age, created_at, updated_at
            FROM users
            ORDER BY id DESC;
          `,
          values: [],
        };

    const { rows } = await pool.query(query);
    response.json(rows);
  } catch (error) {
    response.status(500).json({ message: "Не удалось получить пользователей.", detail: error.message });
  }
});

app.get("/api/users/:id", async (request, response) => {
  const id = parsePositiveInt(request.params.id);

  if (!id) {
    response.status(400).json({ message: "id должен быть положительным целым числом." });
    return;
  }

  try {
    const { rows } = await pool.query(
      `
        SELECT id, first_name, last_name, age, created_at, updated_at
        FROM users
        WHERE id = $1;
      `,
      [id],
    );

    if (!rows[0]) {
      response.status(404).json({ message: "Пользователь не найден." });
      return;
    }

    response.json(rows[0]);
  } catch (error) {
    response.status(500).json({ message: "Не удалось получить пользователя.", detail: error.message });
  }
});

app.patch("/api/users/:id", async (request, response) => {
  const id = parsePositiveInt(request.params.id);

  if (!id) {
    response.status(400).json({ message: "id должен быть положительным целым числом." });
    return;
  }

  const { payload, errors } = sanitizeUserPayload(request.body, { partial: true });

  if (errors.length) {
    response.status(400).json({ message: "Ошибка валидации.", errors });
    return;
  }

  const fields = Object.keys(payload);
  const assignments = fields.map((field, index) => `${field} = $${index + 1}`).join(", ");
  const values = fields.map((field) => payload[field]);

  try {
    const { rows } = await pool.query(
      `
        UPDATE users
        SET ${assignments}
        WHERE id = $${values.length + 1}
        RETURNING id, first_name, last_name, age, created_at, updated_at;
      `,
      [...values, id],
    );

    if (!rows[0]) {
      response.status(404).json({ message: "Пользователь не найден." });
      return;
    }

    response.json(rows[0]);
  } catch (error) {
    response.status(500).json({ message: "Не удалось обновить пользователя.", detail: error.message });
  }
});

app.delete("/api/users/:id", async (request, response) => {
  const id = parsePositiveInt(request.params.id);

  if (!id) {
    response.status(400).json({ message: "id должен быть положительным целым числом." });
    return;
  }

  try {
    const { rows } = await pool.query(
      `
        DELETE FROM users
        WHERE id = $1
        RETURNING id;
      `,
      [id],
    );

    if (!rows[0]) {
      response.status(404).json({ message: "Пользователь не найден." });
      return;
    }

    response.json({ message: "Пользователь удален.", id });
  } catch (error) {
    response.status(500).json({ message: "Не удалось удалить пользователя.", detail: error.message });
  }
});

app.use((request, response) => {
  response.sendFile(path.join(ROOT_DIR, "index.html"));
});

initDatabase()
  .then(() => {
    app.listen(PORT, HOST, () => {
      console.log(`Server is running on http://${HOST}:${PORT}`);
    });
  })
  .catch((error) => {
    console.error("Не удалось подготовить базу данных:", error.message);
    if (error.code === "ENETUNREACH" && String(error.address || "").includes(":")) {
      console.error(
        "Supabase direct connection использует IPv6. Для этой среды укажите в DATABASE_URL строку Session Pooler из Supabase Dashboard -> Connect -> Session pooler.",
      );
    }
    process.exit(1);
  });
